/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as AbstractSubmissionRouteImport } from './routes/abstract-submission'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConferencesIndexRouteImport } from './routes/conferences.index'
import { Route as RegisterIdRouteImport } from './routes/register.$id'
import { Route as ConferencesIdRouteImport } from './routes/conferences.$id'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AbstractSubmissionRoute = AbstractSubmissionRouteImport.update({
  id: '/abstract-submission',
  path: '/abstract-submission',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesIndexRoute = ConferencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConferencesRoute,
} as any)
const RegisterIdRoute = RegisterIdRouteImport.update({
  id: '/register/$id',
  path: '/register/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesIdRoute = ConferencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConferencesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abstract-submission': typeof AbstractSubmissionRoute
  '/conferences': typeof ConferencesRouteWithChildren
  '/contact': typeof ContactRoute
  '/conferences/$id': typeof ConferencesIdRoute
  '/register/$id': typeof RegisterIdRoute
  '/conferences/': typeof ConferencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abstract-submission': typeof AbstractSubmissionRoute
  '/contact': typeof ContactRoute
  '/conferences/$id': typeof ConferencesIdRoute
  '/register/$id': typeof RegisterIdRoute
  '/conferences': typeof ConferencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abstract-submission': typeof AbstractSubmissionRoute
  '/conferences': typeof ConferencesRouteWithChildren
  '/contact': typeof ContactRoute
  '/conferences/$id': typeof ConferencesIdRoute
  '/register/$id': typeof RegisterIdRoute
  '/conferences/': typeof ConferencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abstract-submission'
    | '/conferences'
    | '/contact'
    | '/conferences/$id'
    | '/register/$id'
    | '/conferences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abstract-submission'
    | '/contact'
    | '/conferences/$id'
    | '/register/$id'
    | '/conferences'
  id:
    | '__root__'
    | '/'
    | '/abstract-submission'
    | '/conferences'
    | '/contact'
    | '/conferences/$id'
    | '/register/$id'
    | '/conferences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbstractSubmissionRoute: typeof AbstractSubmissionRoute
  ConferencesRoute: typeof ConferencesRouteWithChildren
  ContactRoute: typeof ContactRoute
  RegisterIdRoute: typeof RegisterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abstract-submission': {
      id: '/abstract-submission'
      path: '/abstract-submission'
      fullPath: '/abstract-submission'
      preLoaderRoute: typeof AbstractSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences/': {
      id: '/conferences/'
      path: '/'
      fullPath: '/conferences/'
      preLoaderRoute: typeof ConferencesIndexRouteImport
      parentRoute: typeof ConferencesRoute
    }
    '/register/$id': {
      id: '/register/$id'
      path: '/register/$id'
      fullPath: '/register/$id'
      preLoaderRoute: typeof RegisterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences/$id': {
      id: '/conferences/$id'
      path: '/$id'
      fullPath: '/conferences/$id'
      preLoaderRoute: typeof ConferencesIdRouteImport
      parentRoute: typeof ConferencesRoute
    }
  }
}

interface ConferencesRouteChildren {
  ConferencesIdRoute: typeof ConferencesIdRoute
  ConferencesIndexRoute: typeof ConferencesIndexRoute
}

const ConferencesRouteChildren: ConferencesRouteChildren = {
  ConferencesIdRoute: ConferencesIdRoute,
  ConferencesIndexRoute: ConferencesIndexRoute,
}

const ConferencesRouteWithChildren = ConferencesRoute._addFileChildren(
  ConferencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbstractSubmissionRoute: AbstractSubmissionRoute,
  ConferencesRoute: ConferencesRouteWithChildren,
  ContactRoute: ContactRoute,
  RegisterIdRoute: RegisterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
